services:
  docs:
    image: blogging_platform_api_local_docs
    container_name: blogging_platform_api_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./blogging_platform_api:/app/blogging_platform_api:z
    ports:
      - '9000:9000'
    command: /start-docs
